DVDNAME=lubuntu-18.04-desktop-amd64		# Ubuntu LiveCD DVDNAME
ISODIR=./				# Path to original ISO
LIVEDIR=./live			# Directory for building

PACKAGES="mc htop openssh-server net-tools"	# Packages that have to be installed
RM_PACKAGES="hunspell* language-pack-* abiword-common* firefox pidgin-data gnumeric-common fonts-noto-cjk geoip-database yudit-common firefox-* sylphee* mtpaint transmission-common libsane-common audacious" #Packages to remove
